### ISSUE TITLE
there is error

### ISSUE THREAD

**Issue by yuruotong1** [miao1007/hexo-filter-kroki#3]
```error
https://github.com/highlightjs/highlight.js/issues/2277
FATAL {
  err: Template render error: (unknown path)
    unexpected end of file
      at Object._prettifyError (D:\tec\my_blogs\node_modules\nunjucks\src\lib.js:36:11)
      at Template.render (D:\tec\my_blogs\node_modules\nunjucks\src\environment.js:538:21)       
      at Environment.renderString (D:\tec\my_blogs\node_modules\nunjucks\src\environment.js:380:17)
      at D:\tec\my_blogs\node_modules\hexo\lib\extend\tag.js:236:16
      at tryCatcher (D:\tec\my_blogs\node_modules\bluebird\js\release\util.js:16:23)
      at Function.Promise.fromNode.Promise.fromCallback (D:\tec\my_blogs\node_modules\bluebird\js\release\promise.js:209:30)
      at Tag.render (D:\tec\my_blogs\node_modules\hexo\lib\extend\tag.js:235:20)
      at Object.onRenderEnd (D:\tec\my_blogs\node_modules\hexo\lib\hexo\post.js:297:22)
      at D:\tec\my_blogs\node_modules\hexo\lib\hexo\render.js:79:21
      at tryCatcher (D:\tec\my_blogs\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (D:\tec\my_blogs\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (D:\tec\my_blogs\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (D:\tec\my_blogs\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (D:\tec\my_blogs\node_modules\bluebird\js\release\promise.js:729:18)
      at _drainQueueStep (D:\tec\my_blogs\node_modules\bluebird\js\release\async.js:93:12)       
      at _drainQueue (D:\tec\my_blogs\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (D:\tec\my_blogs\node_modules\bluebird\js\release\async.js:102:5)    
      at Immediate.Async.drainQueues (D:\tec\my_blogs\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (internal/timers.js:456:21) {
    cause: Template render error: (unknown path)
      unexpected end of file
        at Object._prettifyError (D:\tec\my_blogs\node_modules\nunjucks\src\lib.js:36:11)        
        at Template.render (D:\tec\my_blogs\node_modules\nunjucks\src\environment.js:538:21)     
        at Environment.renderString (D:\tec\my_blogs\node_modules\nunjucks\src\environment.js:380:17)
        at D:\tec\my_blogs\node_modules\hexo\lib\extend\tag.js:236:16
        at tryCatcher (D:\tec\my_blogs\node_modules\bluebird\js\release\util.js:16:23)
        at Function.Promise.fromNode.Promise.fromCallback (D:\tec\my_blogs\node_modules\bluebird\js\release\promise.js:209:30)
        at Tag.render (D:\tec\my_blogs\node_modules\hexo\lib\extend\tag.js:235:20)
        at Object.onRenderEnd (D:\tec\my_blogs\node_modules\hexo\lib\hexo\post.js:297:22)        
        at D:\tec\my_blogs\node_modules\hexo\lib\hexo\render.js:79:21
        at tryCatcher (D:\tec\my_blogs\node_modules\bluebird\js\release\util.js:16:23)
        at Promise._settlePromiseFromHandler (D:\tec\my_blogs\node_modules\bluebird\js\release\promise.js:547:31)
        at Promise._settlePromise (D:\tec\my_blogs\node_modules\bluebird\js\release\promise.js:604:18)
        at Promise._settlePromise0 (D:\tec\my_blogs\node_modules\bluebird\js\release\promise.js:649:10)
        at Promise._settlePromises (D:\tec\my_blogs\node_modules\bluebird\js\release\promise.js:729:18)
        at _drainQueueStep (D:\tec\my_blogs\node_modules\bluebird\js\release\async.js:93:12)     
        at _drainQueue (D:\tec\my_blogs\node_modules\bluebird\js\release\async.js:86:9)
        at Async._drainQueues (D:\tec\my_blogs\node_modules\bluebird\js\release\async.js:102:5)  
        at Immediate.Async.drainQueues (D:\tec\my_blogs\node_modules\bluebird\js\release\async.js:15:14)
        at processImmediate (internal/timers.js:456:21) {
      name: 'Template render error'
    },
    isOperational: true
  }
} Something's wrong. Maybe you can find the solution here: %s https://hexo.io/docs/troubleshooting.html
```

**Comment by miao1007** [comment]
Provide any md or config example？
